### ISSUE TITLE
Questions about sample.vcf in step1

### ISSUE THREAD

**Issue by WZo0o** [Virginiaxu/DeepMosaic#10]
Hello，
I noticed that while using MuTect2 single model you recommend "PASS" vcfs as input for DeepMosaic. 
Is the command parameter of MuTect2 single model similiar as "gatk Mutect2 -R reference.fa -I sample.bam -O single_sample.vcf.gz"? AND how to generate "PASS" vcfs?
Could you help me?

**Comment by shishenyxx** [comment]
> Hello， I noticed that while using MuTect2 single model you recommend "PASS" vcfs as input for DeepMosaic. Is the command parameter of MuTect2 single model similiar as "gatk Mutect2 -R reference.fa -I sample.bam -O single_sample.vcf.gz"? AND how to generate "PASS" vcfs? Could you help me?

Hi WZo0o 

Thank you for your question, you can follow the following snakemake pipeline as an example.

https://github.com/shishenyxx/Adult_brain_somatic_mosaicism/tree/master/pipelines/WGS_SNV_indel_calling_pipeline/Mutect2_single_mode

The pipeline follows the GATK MuTect2 single mode official guides, starting from split intervals (if you have an entire genome to screen), run MuTect2, generated panel of normal, and run MuTect2 single mode, all the way down to extract filtered and passed.

Details are documented in https://gatk.broadinstitute.org/hc/en-us/articles/360037227652-CreateSomaticPanelOfNormals-BETA- and https://gatk.broadinstitute.org/hc/en-us/articles/360037593851-Mutect2

I will also update this in the main tutorial. Thank you again for your question! Please do not hesitate to reach out if you have any further questions!

All the best,

Xiaoxu

**Comment by WZo0o** [comment]
Hi, shishenyxx

Thanks for your help. 

DeepMosaic is designed to run without control samples, but the GATK MuTect2 single-mode official guides seem still need unmatched control samples. 

Is my point correct?

**Comment by shishenyxx** [comment]
> Hi, shishenyxx
> 
> Thanks for your help.
> 
> DeepMosaic is designed to run without control samples, but the GATK MuTect2 single-mode official guides seem still need unmatched control samples.
> 
> Is my point correct?

Hi,

Yeah if you are using GATK MuTect2 single mode it needs it, while if you are using GATK haolotypecaller ploidy 50 it doesn't; require a panel of normal.

Either could serve as input for DeepMosaic.

Best,

Xiaoxu

**Comment by WZo0o** [comment]
Hi, Xiaoxu

Which will be a better pipeline to serve as input for DeepMosaic between MuTect2 and haolotypecaller?

Best,

Zheng Wang

**Comment by shishenyxx** [comment]
> Hi, Xiaoxu
> 
> Which will be a better pipeline to serve as input for DeepMosaic between MuTect2 and haolotypecaller?
> 
> Best,
> 
> Zheng Wang

Hi Zheng,

From our own experience and others' preliminary data, MuTect2 single (tumor-only) mode has better performance. 

Best,

Xiaoxu

**Comment by WZo0o** [comment]
Hi, Xiaoxu

Thanks for your reply.

Best,

Zheng Wang
