### ISSUE TITLE
A little issue in canvasPainter.py

### ISSUE THREAD

**Issue by Lidweixiang** [Virginiaxu/DeepMosaic#13]
Hi, Dr. Yang.

The canvasPainter.py code in DeepMosaic:

Line 38, maybe should replace 'offset = 0' using  'offset = int(start-start_pos)'
Because a deletion may occur which will lead to 'start != start_pos'

The windows 'width/2=150bp' is longer than most Illumina sequencing, so 'line38' is less to be used.
So the issue won't affect you too much in your training, but maybe this issue indeed exists.

Best regards,
Weixiang

**Comment by shishenyxx** [comment]
> Weixiang

Hi Weixiang,

Thank you for pointing this out, we updated it for now according to your suggestions and will see whether this causes troubles elsewhere. Thank you for helping to make DeepMosaic better!

Best,

Xiaoxu
