### ISSUE TITLE
different gnomad databases?

### ISSUE THREAD

**Issue by apaul7** [Virginiaxu/DeepMosaic#17]
Hello!
Thank you for making this program!
I believe that the the hg19/hg38 gnomad annotations are somewhat hardcoded into the program. Specifically to v2.0.1, which for hg38 is installed with annovar at `hg38_ gnomad_genome.txt`. I only have the newer versions of gnomad downloaded in my annovar installation. 
- hg38_gnomad312_genome.txt
- hg38_gnomad30_genome.txt
- hg38_gnomad211_genome.txt

Could you create an input option to control what version of gnomad is used for annotations?
I got around the error:
```
Error: the database file /annovar/annovar/humandb/hg38_gnomad_genome.txt is not present
```
by symlinking `hg38_gnomad312_genome.txt` to `hg38_ gnomad_genome.txt`. Which works but is not an ideal solution.

**Comment by shishenyxx** [comment]
Option added and the tutorial and singularity will be updated. We will release a new subversion. Thank you so much for your feedback!

Best,

Arzoo and Xiaoxu
