### ISSUE TITLE
About SimData

### ISSUE THREAD

**Issue by songbowang125** [Virginiaxu/DeepMosaic#3]
Hi, I am reading your papar on Nature Biotechnology and get confused about your SimDatas

1. For SimData1 and SimData2, did you simulate those variants (10,000 and 7,610, respectively) via Pysim? or just manually create those variants?
2. For SimData3,  if I understand correctly, those 30,090 variants were obtained from GIAB's callset on HG002. However, what did you mean by 'original BAM file' (In Method-SimData3 section, The original BAM file was first up-sampled, and alternative reads were replaced to generate the expected AF)? How did you obtain or generate the 'original BAM file'?

Thanks and looking forward to your reply

**Comment by shishenyxx** [comment]
Thank you for your questions!

1. For SimData1 and SimData2 we first simulate wildtype and alternative sequences (het) with Pysim and sample them at different ratios to get the designated allelic fractions. SimData1 and SimData2 followed different sequencing error models.
2. We first downloaded the raw bam file of HG002, up-sample, and down-sample the genome sequences to get the designated depth. We scanned the genome from the original deep whole genome sequences, for mutation-negative regions, we replaced some reads with designed mutant alleles with BAMSurgeon.
Please do not hesitate to contact us if you have further questions!

Happy New Year!

Best,

Xiaoxu

**Comment by songbowang125** [comment]
Thanks a lot for your answer. I understand that you used origin HG002 to retain the sequencing errors, which might cause a lot misjudgements of SNVs, especially mosaic SNVs. And this process makes the simulated data closer to a real one.

But I am still a little confused about the generation steps of SimData3.

As I understand it, you created SimData3 following three steps:

1. Select 30,090 homozygous variants from HG002 chr1.
2. Wtih BAMSrugeon, you inserted (added) those 30,090 variants into mutation-negative regions of up/down-sampled HG002 with designed mutant alleles.
3. Those mutation-negative regions fulfill the three criteria mentioned in your paper: (1) zero alternative bases, (2) no indels and (3) at least 1,000 bases between each other.

Are the three steps similar as yours?

Happy New Year!

**Comment by shishenyxx** [comment]
Hi Songbo,

Yeah, that's similar, to be more specific, 
1. We scan the genome of HG002 to get regions that are alternative base-negative and indel-free
2. We randomly generated a list of genomic positions within those regions, and filtered them down under the criteria that they are at least 1,000 bases between each other on the chromosome.
3. For each of the up/down-sampled HG002 file, BAMSurgeon takes the original reference reads, replaces one base at a certain fraction, then map the reads back to the genome and merge them into a new bam.

Hope that helps!

Best,

Xiaoxu

**Comment by shishenyxx** [comment]
Thanks a lot for your answer. I understand that you used origin HG002 to retain the sequencing errors, which might cause a lot of misjudgments of SNVs, especially mosaic SNVs. And this process makes the simulated data closer to a real one.

But I am still a little confused about the generation steps of SimData3.

As I understand it, you created SimData3 following three steps:

    Select 30,090 homozygous variants from HG002 chr1.
    Wtih BAMSrugeon, you inserted (added) those 30,090 variants into mutation-negative regions of up/down-sampled HG002 with designed mutant alleles.
    Those mutation-negative regions fulfill the three criteria mentioned in your paper: (1) zero alternative bases, (2) no indels and (3) at least 1,000 bases between each other.

Are the three steps similar as yours?

Happy New Year!

**Comment by shishenyxx** [comment]
Hi Songbo,

Sorry I accidentally deleted your post. Was trying to restore it.

Yeah using BAMsurgeon we are retaining sequencing errors, SNPs, and haplotype information which makes it closer to the real data.

1. We scanned the genome and selected the alt-read-negative and indel-negative regions.
2. We randomly generated a list of variants, and filtered it down under the criteria that they have to be at least 1kp apart.
3. With BAMsurgeon we replace the original HG002 sequences (down-sampled or up-sampled) with added mutations and align them back to the genome to generate a newly merged bam.

Hope that helps you!

Xiaoxu

**Comment by songbowang125** [comment]
Oh, I got it! Now I am clear about your simulations. DeepMosaic is a wonderful job and helps me with my own project. Thanks again.

Best, 
Songbo

**Comment by shishenyxx** [comment]
> Oh, I got it! Now I am clear about your simulations. DeepMosaic is a wonderful job and helps me with my own project. Thanks again.
> 
> Best, Songbo

Hi Songbo,

Glad to help! Thank you for trying DeepMosaic!

Best,

Xiaoxu

**Comment by shishenyxx** [comment]
Detailed info added to the wiki page https://github.com/Virginiaxu/DeepMosaic/wiki
