### ISSUE TITLE
running DeepMosaic with hg38

### ISSUE THREAD

**Issue by tgambin** [Virginiaxu/DeepMosaic#4]
Hi, I am trying to run DeepMosaic with hg38 and I found one resource is missing:

'Error: The requested file (/resources/all_repeats.hg38.bed) could not be opened. Error message: (No such file or directory). Exiting!'

Do you have this file ? Or could you provide description how to generate it?
Thanks!

**Comment by shishenyxx** [comment]
> Hi, I am trying to run DeepMosaic with hg38 and I found one resource is missing:
> 
> 'Error: The requested file (/resources/all_repeats.hg38.bed) could not be opened. Error message: (No such file or directory). Exiting!'
> 
> Do you have this file ? Or could you provide description how to generate it? Thanks!

Hi, we have added all_repeats.b38.bed and segdup.hg38.bed to the resource folder.

They were just generated from UCSC genome browser, sorted and merged with bedtools.

Best,

Xiaoxu

**Comment by tgambin** [comment]
Thanks! Now it works and I was able to get predictions to my mosaic variants :).

**Comment by shishenyxx** [comment]
> Thanks! Now it works and I was able to get predictions to my mosaic variants :).

Glad to hear that. Thank you for your interest in DeepMosaic!
