### ISSUE TITLE
speed up step 1?

### ISSUE THREAD

**Issue by kunalkathuria** [Virginiaxu/DeepMosaic#8]
Hello,

I was trying to process a list of 4 million putative SNVs with your tool. Wondering if there's a way to speed up processing? It's been running for quite a few days. Would you advise running batches of variants independently and assembling the predictions at the end? Thanks!

Kunal

**Comment by shishenyxx** [comment]
Hi Kunal,

Thank you for your question, please split the input for both steps and you can always combine the output at the end.

Best,

Xiaoxu

**Comment by kunalkathuria** [comment]
Great, thanks!
