### ISSUE TITLE
high maf and score3 simultaneously?

### ISSUE THREAD

**Issue by kunalkathuria** [Virginiaxu/DeepMosaic#9]
Hi Xiaoxu,

I observed cases where the variant allele frequency was 1.0 and yet score3 was very high (though prediction was not "mosaic"):

 grep -w -F -f pred.common.snv.txt prediction_all_batches.dlpfc.no_artif_intronic.txt | awk '$21 > .9' | cut -f3-8,11,19,21-22 | head
chr10   56646808        T       C       chr10_56646808_T_C      1.0     intergenic      0.08634431215220496     0.9056392422676766      alternative_homozygous
chr10   64154450        T       A       chr10_64154450_T_A      0.9583333333333334      intergenic      0.05680040770804196     0.9114665426861789      alternative_homozygous
chr10   64263645        A       G       chr10_64263645_A_G      1.0     intergenic      0.035593511213016175    0.9638000832314269      alternative_homozygous
chr10   69640841        G       C       chr10_69640841_G_C      1.0     intergenic      0.06964778067165234     0.9294363717543487      alternative_homozygous
chr10   64890126        C       T       chr10_64890126_C_T      1.0     intergenic      0.014043077162248046    0.9857749298484482      alternative_homozygous

Wondering how an maf = 1.0, which would typically indicate a germline variant, can have a high mosaic score. The 6th column is maf, 8th is score 1 and 9th is score3 above.

Thanks again!

Kunal

**Comment by shishenyxx** [comment]
> 

Hi Kunal,

Thank you for the question, and you raised a very good point. The reason we don't directly use scores but use a combined classifier at the end of DeepMosaic pipeline is the scores by training are not merely homo, het, or mosaic status, they are highly influenced by the genotype but also contain a lot additional information. Thus we encourage you to use the final output fromDeepMosaic. You can pull out the images and see.

Best,

Xiaoxu

**Comment by kunalkathuria** [comment]
Thanks, Xiaoxu, will do.

Best,

Kunal
